# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123udolwFeLl8gVcFBNoS5K6QIyDqS38h

IMPORTING LIBRARIES
"""

import sqlite3, string
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import spacy
import nltk

from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from wordcloud import WordCloud

for pkg in['vader_lexicon','stopwords','wordnet','averaged_perceptron_tagger']:
  nltk.download(pkg,quiet=True)
nlp=spacy.load('en_core_web_sm')
print("all libraries loaded successfully")

"""CREATE SQLITE DATABASE"""

np.random.seed(7)
N=1000
categories=['Electronics','Clothing','Books','Home','Sports']
REVIEWS=['Absolutely love this product, works perfectly and arrived quickly',
'Terrible quality, it broke after one week. Very disappointed.',
'Decent product but the shipping was extremely slow.',
'Great value for money, I highly recommend it to everyone.',
'Not as described. The colour was completely wrong.',
'Battery life is amazing — best purchase I have made this year!',
'Returns process was smooth. Product itself is just average.',
'Exactly what I needed. Fast delivery and great packaging.',
'Poor customer service, took two weeks to get a response.',
'Exceeded expectations. Premium quality at a fair price.',
'The product stopped working after three uses. Waste of money.',
'Good product overall but the instructions were very confusing.',]

df=pd.DataFrame({'customer_id':np.arange(1,N+1),
                 'product_id':np.random.randint(1,101,N),
                 'product_category':np.random.choice(categories,N),
                 'rating':np.random.choice([1,2,3,4,5],N,p=[0.10,0.10,0.15,0.30,0.35]),
                 'review_text':np.random.choice(REVIEWS,N),
                 'review_date':pd.date_range('2023-01-01',periods=N,freq='7h').astype(str),
                 'num_orders':np.random.randint(1,35,N),
                 'total_spend':np.random.uniform(20,6000,N).round(2),
                 'num_returns':np.random.randint(0,8,N),})

conn = sqlite3.connect('ecommerce.db')
df.to_sql('reviews', conn, if_exists='replace', index=False)
print(f'Database created: {N} rows in ecommerce.db')

"""SQL QUERIES"""

import pandas as pd
import sqlite3
import numpy as np

N=1000
categories=['Electronics','Clothing','Books','Home','Sports']
REVIEWS=['Absolutely love this product, works perfectly and arrived quickly',
'Terrible quality, it broke after one week. Very disappointed.',
'Decent product but the shipping was extremely slow.',
'Great value for money, I highly recommend it to everyone.',
'Not as described. The colour was completely wrong.',
'Battery life is amazing — best purchase I have made this year!',
'Returns process was smooth. Product itself is just average.',
'Exactly what I needed. Fast delivery and great packaging.',
'Poor customer service, took two weeks to get a response.',
'Exceeded expectations. Premium quality at a fair price.',
'The product stopped working after three uses. Waste of money.',
'Good product overall but the instructions were very confusing.',]

df_data=pd.DataFrame({'customer_id':np.arange(1,N+1),
                 'product_id':np.random.randint(1,101,N),
                 'product_category':np.random.choice(categories,N),
                 'rating':np.random.choice([1,2,3,4,5],N,p=[0.10,0.10,0.15,0.30,0.35]),
                 'review_text':np.random.choice(REVIEWS,N),
                 'review_date':pd.date_range('2023-01-01',periods=N,freq='7h').astype(str),
                 'num_orders':np.random.randint(1,35,N),
                 'total_spend':np.random.uniform(20,6000,N).round(2),
                 'num_returns':np.random.randint(0,8,N),})

conn = sqlite3.connect('ecommerce.db')
df_data.to_sql('reviews', conn, if_exists='replace', index=False) # Ensure table exists and is populated


df=pd.read_sql_query('Select * from reviews',conn)
q_cat=pd.read_sql_query(""" select product_category, round(AVG(rating),2) as avg_rating, count(*) as review_count from reviews
group by product_category
order by avg_rating desc""",conn)
print("Ratings by category:\n",q_cat)

q_hvip=pd.read_sql_query(''' select customer_id,num_orders,total_spend,num_returns,rating from reviews
where total_spend>3000 and num_orders>=15
order by total_spend desc
limit 15
''',conn)
print("High-value customers:\n",q_hvip)

q_comp=pd.read_sql_query(''' select customer_id,rating,num_returns,review_text from reviews
where rating<=2 and num_returns>=3
order by num_returns desc
''',conn)
print('Complaint customers:\n',q_comp.head(10))

"""NLP TEXT PREPROCESSING WITH NLTK"""

import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()
def preprocessor_text(text):
  ''' Pipeline:lowercase → remove punctuation → tokenise →
      remove stop-words → lemmatise → rejoin
  '''
  text=text.lower()
  text=text.translate(str.maketrans('','',string.punctuation))
  tokens=word_tokenize(text)
  tokens=[t for t in tokens if t not in stop_words and t.isalpha()]
  tokens=[lemmatizer.lemmatize(t) for t in tokens]
  return ''.join(tokens)
df['clean_review']=df['review_text'].apply(preprocessor_text)
print(df[['review_text','clean_review']].head(4).to_string())

"""SENTIMENT ANALYZER USING VADER"""

sia=SentimentIntensityAnalyzer()
def classify_sentiment(text):
  scores=sia.polarity_scores(text)
  compound=scores['compound']
  if compound>=0.05:
    return 'Positive'
  elif compound<=-0.05:
    return 'Negative'
  else:
    return 'Netural'
df['compound_score']=df['review_text'].apply(
    lambda x:sia.polarity_scores(x)['compound'])
df['sentiment']=df['review_text'].apply(classify_sentiment)
print('Sentiment Distribution:')
print(df['sentiment'].value_counts())
print(df[['review_text','compound_score','sentiment']].head(5))
cross= pd.crosstab(df['product_category'], df['sentiment'], normalize='index') *100
cross.plot(kind='bar', stacked=True, figsize=(11,5),
color=['#E74C3C','#F39C12','#27AE60'])
plt.title('Sentiment Distribution by Product Category (%)')
plt.ylabel('Percentage'); plt.xticks(rotation=0)
plt.legend(loc='upper right')
plt.tight_layout()
plt.savefig('sentiment_by_category.png', dpi=150, bbox_inches='tight')
plt.show()

"""NAME ENTITY RECOGNITION WITH SPACY"""

def extract_entities(text):
  ''' return list of (entity_text,entity_label) tuples.'''
  doc=nlp(text)
  return[(ent.text,ent.label_)for ent in doc.ents]
def get_noun_phrases(text):
  '''extract multi-word noun phrases using spacy dependency parser.'''
  doc=nlp(text)
  return[chunk.text.lower() for chunk in doc.noun_chunks
         if len(chunk.text.split())>1]
df['entities']=df['review_text'].apply(extract_entities)
df['noun_phrases']=df['review_text'].apply(get_noun_phrases)
sample=df[df['entities'].apply(len)>0][['review_text','entities']].head(6)
print(sample.to_string())
from collections import Counter
all_entities=[e for sublist in df['entities'] for e in sublist]
label_freq=Counter(label for _,label in all_entities)
print('Entity label frequency:',label_freq.most_common(8))
doc=nlp('The battery life is amazing but shipping was very slow.')
for token in doc:
   print(f'{token.text:<15} POS:{token.pos_:8} DEP:{token.dep_}')

"""CUSTOMER SEGMENTAION USING K-MEANS CLUSTER"""

cluster_feats=['num_orders','total_spend','num_returns','rating','compound_score']
X_c=df[cluster_feats].copy()
scaler_c=StandardScaler()
X_scaled=scaler_c.fit_transform(X_c)
inertias=[]
silhouettes=[]
K_range=range(2,11)
for k in K_range:
  km=KMeans(n_clusters=k,random_state=42,n_init=15,max_iter=300)
  labels=km.fit_predict(X_scaled)
  inertias.append(km.inertia_)
  silhouettes.append(silhouette_score(X_scaled,labels))
fig,(ax1,ax2)=plt.subplots(1,2,figsize=(13,5))
ax1.plot(list(K_range),inertias, 'bo-', linewidth=2, markersize=8)
ax1.set(title='Elbow Method — Inertia vs K',
xlabel='Number of Clusters (K)', ylabel='Inertia (WCSS)')
ax1.grid(True, alpha=0.3)
ax2.plot(list(K_range), silhouettes, 'rs-', linewidth=2, markersize=8)
ax2.set(title='Silhouette Score vs K',
xlabel='Number of Clusters (K)', ylabel='Silhouette Score')
ax2.grid(True, alpha=0.3)
plt.suptitle('Choosing Optimal K for K-Means', fontsize=13)
plt.tight_layout()

plt.savefig('elbow_silhouette.png', dpi=150, bbox_inches='tight')
plt.show()

"""FINAL K-MEANS CLUSTER AND PROFILE EACH CLUSTER"""

OPTIMAL_K = 4
kmeans = KMeans(n_clusters=OPTIMAL_K, random_state=42, n_init=20, max_iter=500)
df['cluster'] = kmeans.fit_predict(X_scaled)
print("Cluster size distribution:")
print(df["cluster"].value_counts().sort_index())
profile = df.groupby("cluster")[cluster_feats].mean().round(2)
print("\nCluster Profile (Mean Values):")
print(profile.to_string())
sent_profile = df.groupby("cluster")["sentiment"].value_counts(normalize=True).unstack(fill_value
=0)
print("\nSentiment breakdown per cluster:")
print((sent_profile * 100).round(1))
cat_profile = df.groupby("cluster")["product_category"].agg(lambda x:
x.value_counts().index[0])
print("\nTop category per cluster:")
print(cat_profile)

"""FINAL REPORT"""

output_cols = ['customer_id','product_category','rating',
'compound_score','sentiment','cluster']
df[output_cols].to_sql('enriched_reviews', conn,
if_exists='replace', index=False)
summary = pd.read_sql_query('''
SELECT cluster,
COUNT(*) AS customer_count,
ROUND(AVG(compound_score),3) AS avg_sentiment_score,
ROUND(AVG(rating),2) AS avg_star_rating,
GROUP_CONCAT(DISTINCT sentiment) AS sentiment_types
FROM enriched_reviews
GROUP BY cluster
ORDER BY cluster
''', conn)
print('\nFinal Cluster Summary from SQL:')
print(summary.to_string())
df.to_csv('customer_segmentation_report.csv', index=False)
print('Report exported: customer_segmentation_report.csv')